---
# tasks file for setup-configs


- name: Insert a line at the end of a file.
  become: no
  lineinfile:
    path: "/home/timo/.bashrc"
    line: export PS1="\[\033[1;36m\]me\[\033[01;37m\]@\[\033[01;34m\]me\[\033[01;30m\][\[\033[01;37m\]\w\[\033[01;30m\]]\[\033[01;32m\]\[\033[00m\]+ "
